apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saldo-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GabrielSosa/desafio-devops-farinter.git
    targetRevision: HEAD
    path: k8s
    # ArgoCD detectará automáticamente kustomization.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
